### ISSUE TITLE
DiscriminatorNode access on undefined property

### ISSUE THREAD

**Issue by pmarschik** [PaloAltoNetworks/docusaurus-openapi-docs#1026]
## Describe the bug

With version 4.2.0 OAS discriminator was changed and now results in "This page crashed": `TypeError: undefined is not an object (evaluating 'subProperties[discriminator.propertyName]')` errors.

Rolling back to 4.1.0 fixes the issue but shows "circular(InnerClassTypeA)".

## Your Environment

- Version used: 4.2.0

## Context

The relevant part of redacted OAS looks like this:

```yml
# ...
components:
  schemas:
    OuterClass:
      type: object
      properties:
        _TYPE:
          type: string
          enum:
            - type1
            - type2
        sharedProperty:
          type: string
     discriminator:
       propertyName: _TYPE
       mapping:
         type1: "#components/schemas/OuterClassType1"
         type2: "#components/schemas/OuterClassType2"
    OuterClassType1:
      allOf:
        - $ref: "#components/schemas/OuterClass"
        - type: object
          properties:
            # property named the same but different concrete schema per discriminated property
            innerClass:
              $ref: "#components/schemas/InnerClassTypeA"
    OuterClassType2:
      allOf:
        - $ref: "#components/schemas/OuterClass"
        - type: object
          properties:
            # property named the same but different concrete schema per discriminated property
            innerClass:
              $ref: "#components/schemas/InnerClassTypeB"
    # never used directly but only "inherited" from with allOf
    InnerClass:
      type: object
      properties:
        _TYPE:
          type: string
          enum:
            - typeA
            - typeB
        sharedProperty:
          type: string
     discriminator:
       propertyName: _TYPE
       mapping:
         type1: "#components/schemas/InnerClassTypeA"
         type2: "#components/schemas/InnerClassTypeB"
    InnerClassTypeA:
      allOf:
        - $ref: "#components/schemas/InnerClass"
        - type: object
          properties:
            specificFieldA:
              type: string
    InnerClassTypeB:
      allOf:
        - $ref: "#components/schemas/InnerClass"
        - type: object
          properties:
            specificFieldB:
              type: string
```

**Comment by omonk** [comment]
PR this was introduced in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1009 

We're seeing the same issue as our schema is missing the `properties` when there is a discriminator 

```yaml
BaseNested:
  type: object
  discriminator:
    propertyName: type
  # properties: <---- Missing this properties value here
  #   type:
  #     type: string
  oneOf:
    - $ref: "#/components/schemas/NestedTypeA"
    - $ref: "#/components/schemas/NestedTypeB"

```

Related lines

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/1bd7b94b718ae7c7c2a2e25c91cd076acfcb7d99/packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx#L320

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/1bd7b94b718ae7c7c2a2e25c91cd076acfcb7d99/packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx#L353-L356

--- 

I attempted to make some changes to account for the missing schema.properties value. It's only used to resolve the schema type, which assumed would be possible to grab from the resolved mappings that the `Object.values(discriminator.mappings)` augments

```
  const discriminatorProperty = schema.properties
    ? schema.properties[discriminator.propertyName]
    : discriminator.mapping[0].properties[discriminator.propertyName];

  const schemaName = getSchemaName(discriminatorProperty);
```

I've had to just change the schema with a generic object definition such as

```
properties
  keyName:
    type: object
```

@sserrata any chances you could share some knowledge around here?

Come to think of it, surely the schemaName will _always_ be an object if we're using a discriminator?

**Comment by sserrata** [comment]
Hi @omonk, thanks for help with debugging. This one was a bit tricky but I settled on a fix that I believe should work. I appreciate if you can help test using the latest canary release. Thanks!

**Comment by pmarschik** [comment]
For my usecase the issue persists with 4.3.0, I've worked around it for now by changing my schema:

```yaml
# ...
components:
  schemas:
    OuterClass:
      type: object
      properties:
        _TYPE:
          type: string
          enum:
            - type1
            - type2
        sharedProperty:
          type: string
     discriminator:
       propertyName: _TYPE
       mapping:
         type1: "#components/schemas/OuterClassType1"
         type2: "#components/schemas/OuterClassType2"
    OuterClassType1:
      allOf:
        - $ref: "#components/schemas/OuterClass"
        - type: object
          properties:
            # property named the same but different concrete schema per discriminated property
            innerClass:
              $ref: "#components/schemas/InnerClassTypeA"
    OuterClassType2:
      allOf:
        - $ref: "#components/schemas/OuterClass"
        - type: object
          properties:
            # property named the same but different concrete schema per discriminated property
            innerClass:
              $ref: "#components/schemas/InnerClassTypeB"
    InnerClassTypeA:
      type: object
      properties:
        specificFieldA:
          type: string
    InnerClassTypeB:
      type: object
      properties:
         specificFieldB:
           type: string
```

i.e. I've removed the inheritance on the `InnerClassTypeA` and `InnerClassTypeB`.
