### ISSUE TITLE
Is is possible to customize admonition section for deprecated api?

### ISSUE THREAD

**Issue by redjen8** [PaloAltoNetworks/docusaurus-openapi-docs#1082]
### Is your feature request related to a problem?

I'm creating api doc pages for non native english speakers.
In the case of an api marked with deprecated, I have confirmed that the mdx file is created with the warning admonition automatically.
Can I request this by applying new custom `markdownGenerators` options?

### Describe the solution you'd like

```ts
export function createDeprecationNotice({
  deprecated,
  description,
}: DeprecationNoticeProps) {
  return guard(deprecated, () =>
    createAdmonition({
      children:
        description && description.length > 0
          ? clean(description)
          : "This endpoint has been deprecated and may be replaced or removed in future versions of the API.",
    })
  );
}
```

I wish there was a good way to customize the automatically generated deprecation message (Please check below example)

<img width="702" alt="Image" src="https://github.com/user-attachments/assets/e7607ea7-e781-4841-bb86-d33c35b2373d" />

### Describe alternatives you've considered

Is there any way to customize `createDeprecationNotice` function by applying `markdownGenerators` option?

**Comment by sserrata** [comment]
Hi @redjen8, you can definitely customize this using `markdownGenerators` but are you interested in customizing the description/message or the "⚠ DEPRECATED" title (or both)?

If you just want to change the description, you can use the `x-deprecated-description` extension.

Example:

```
  /pet/findByTags:
    get:
      tags:
        - pet
      summary: Finds Pets by tags
      description: >-
        Multiple tags can be provided with comma separated strings. Use tag1,
        tag2, tag3 for testing.
      operationId: findPetsByTags
      deprecated: true
      x-deprecated-description: "this is a test"
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
...
```

<img width="1270" alt="Image" src="https://github.com/user-attachments/assets/2d22b6f1-e39f-46f3-96d7-962573d08406" />
