### ISSUE TITLE
Swizzling components doesn't work

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#246]
## Describe the problem

I can't figure out why this doesn't work and wondering if other people are running into this. I'm looking to swizzle CodeTabs so I can remove the icons and have it be text only.

After running:

```
npm run swizzle docusaurus-theme-openapi-docs ApiDemoPanel/CodeTabs
```

And choosing either Eject or Wrap I get the proper files in the theme/ folder but modifying them doesn't yield any changes. I tried running `gen-api-docs all` and everything is still the same.

## Suggested fix

Would be great to document how to Swizzle with this plugin.

**Comment by sserrata** [comment]
Hi @sradu, I am still investigating but it should be possible to replace the icons with text using CSS. Still, I think there should be a cleaner way to handle this.

**Comment by sserrata** [comment]
Here's an example of how to override using CSS:

```css
.code__tab--bash {
  padding-left: 1rem !important;
  padding-right: 1rem !important;
}

.code__tab--bash::after {
  background: none !important;
  width: unset !important;
  height: unset !important;
  content: "BASH" !important;
  font-size: 12px !important;
  font-weight: normal !important;
  color: var(--ifm-font-color-base);
}

.code__tab--python {
  padding-left: 1rem !important;
  padding-right: 1rem !important;
}

.code__tab--python::after {
  background: none !important;
  width: unset !important;
  height: unset !important;
  content: "Python" !important;
  font-size: 12px !important;
  font-weight: normal !important;
  color: var(--ifm-font-color-base);
}

.code__tab--go {
  padding-left: 1rem !important;
  padding-right: 1rem !important;
}

.code__tab--go::after {
  background: none !important;
  width: unset !important;
  height: unset !important;
  content: "Go" !important;
  font-size: 12px !important;
  font-weight: normal !important;
  color: var(--ifm-font-color-base);
}

.code__tab--nodejs {
  padding-left: 1rem !important;
  padding-right: 1rem !important;
}

.code__tab--nodejs::after {
  background: none !important;
  width: unset !important;
  height: unset !important;
  content: "NodeJS" !important;
  font-size: 12px !important;
  font-weight: normal !important;
  color: var(--ifm-font-color-base);
}

.code__tab--csharp {
  padding-left: 1rem !important;
  padding-right: 1rem !important;
}

.code__tab--csharp::after {
  background: none !important;
  width: unset !important;
  height: unset !important;
  content: "C#" !important;
  font-size: 12px !important;
  font-weight: normal !important;
  color: var(--ifm-font-color-base);
}
```
