### ISSUE TITLE
Be able to style operation "pills" in output docs

### ISSUE THREAD

**Issue by thomasheartman** [PaloAltoNetworks/docusaurus-openapi-docs#249]
### Is your feature request related to a problem?

The generated pages include operation buttons/pills next to the path. These seem to be rendered as normal docusaurus badges:

![image](https://user-images.githubusercontent.com/17786332/189108073-956ad3d7-e2bd-4ce7-87ee-277888b020ea.png)

There's two issues:

1. The color scheme doesn't necessarily have high enough contrast. That's arguably on us and our configuration, however. 
2. When using the operation buttons next to the buttons (as you do in your examples), there might be a bit of mismatch between the buttons and colors. E.g.:
     Sidebar:
![image](https://user-images.githubusercontent.com/17786332/189108636-74e47df1-2eee-4d3b-b53e-66778b05300f.png)
    Page:
![image](https://user-images.githubusercontent.com/17786332/189108692-4d1a5e89-df35-485d-82ac-f049c7e19faf.png)

The operation pills on the page don't seem to have a distinct class or anything that I can reach into for easy styling purposes.

### Describe the solution you'd like

I'd like to be able to style the pills that appear next to the path, so that we can keep a consistent visual theme going and to ensure that operations use the same colors.

What strikes me as the easiest solution would be to use a similar class naming scheme as you use for the sidebar, adding a class name that matches the operation. Maybe simply adding the operation type to the pill class? 

### Describe alternatives you've considered

I tried looking for some other classes that distinguish the openapi pages from others, but couldn't find any. In theory, we could rewrite _all_ badges to use the color scheme that we use for API operations, but that might impact something else (though I'm not sure we use any badges anywhere today).

### Additional context

I think all context is described above, but I'd be happy to add anything else if you're wondering about anything 😄

**Comment by sradu** [comment]
+1 was just looking into this yesterday and couldn't style the ApiDemoPanel at all. I would also like to tweak the object schemas.


In general would be great to have classes for everything that we could target via css.

**Comment by sserrata** [comment]
We've had internal discussions on this and agree that everything under ApiItem and ApiDemoPanel should have an appropriate class selector. 

Also, we are open to suggestions on how to improve consistency and contrast for the method badges/pills.

**Comment by sserrata** [comment]
Hi @thomasheartman, here's a few things to note/consider:

The method badge style/color is derived from the Infima `badge` class and the supported modifiers, e.g. `badge--success`, `badge--danger`, etc. That said, those colors are in turn based on the built in Imfima color variables, including `--ifm-color-success`, `--ifm-color-primary`, etc. 

Since the sidebar method badge colors are defined entirely in `custom.css`, it's possible you might be specifying colors outside of the `--ifm-color-*` variables or the `--openapi-code-*` colors.

Here's how the `--openapi-code-*` colors map to Infima variables:

```css
:root {
  --openapi-required: var(--ifm-color-danger);
  --openapi-code-blue: var(--ifm-color-info);
  --openapi-code-red: var(--ifm-color-danger);
  --openapi-code-orange: var(--ifm-color-warning);
  --openapi-code-green: var(--ifm-color-success);
}
```

Can you share your `custom.css` you're using to style the sidebar method badges?

**Comment by thomasheartman** [comment]
@sserrata Thanks for the response and glad to hear you've decided to add more class selectors 😄 

Yeah, I figured you did something like that for the colors. For our sake, the "primary" color wasn't really suitable as the "get" method, so we changed the color scheme a bit to keep it more in line with what Swagger UI does. 

> Can you share your custom.css you're using to style the sidebar method badges?

Absolutely! It's based on your [code that you provided as an example](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/02922a6ad6d635373e01409dac8c17a88da2b72e/demo/src/css/custom.css#L45-L95) to [one of the other issues here](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/177), but with a few tweaks.

<details>

<summary>`custom.css badge styling`</summary>

```css
.api-method > .menu__link {
    align-items: center;
    justify-content: start;
}

.api-method > .menu__link::before {
    width: 50px;
    height: 20px;
    font-size: 12px;
    line-height: 20px;
    text-transform: uppercase;
    font-weight: 600;
    border-radius: 0.25rem;
    border: 1px solid;
    border-inline-start-width: 5px;
    margin-right: var(--ifm-spacing-horizontal);
    text-align: center;
    flex-shrink: 0;
}

.get > .menu__link::before {
    content: 'get';
    background-color: var(--ifm-color-info-contrast-background);
    color: var(--ifm-color-info-contrast-foreground);
    border-color: var(--ifm-color-info-dark);
}

.post > .menu__link::before {
    content: 'post';
    background-color: var(--ifm-color-success-contrast-background);
    color: var(--ifm-color-success-contrast-foreground);
    border-color: var(--ifm-color-success-dark);
}

.delete > .menu__link::before {
    content: 'del';
    background-color: var(--ifm-color-danger-contrast-background);
    color: var(--ifm-color-danger-contrast-foreground);
    border-color: var(--ifm-color-danger-dark);
}

.put > .menu__link::before {
    content: 'put';
    background-color: var(--ifm-color-warning-contrast-background);
    color: var(--ifm-color-warning-contrast-foreground);
    border-color: var(--ifm-color-warning-dark);
}

.patch > .menu__link::before {
    content: 'patch';
    background-color: var(--ifm-color-success-contrast-background);
    color: var(--ifm-color-success-contrast-foreground);
    border-color: var(--ifm-color-success-dark);
}

.head > .menu__link::before {
    content: 'head';
    background-color: var(--ifm-color-secondary-contrast-background);
    color: var(--ifm-color-secondary-contrast-foreground);
    border-color: var(--ifm-color-secondary-dark);
}
```

</details>

In short, it usus this bit of CSS for geeral styling:
```css
.api-method > .menu__link::before {
    width: 50px;
    height: 20px;
    font-size: 12px;
    line-height: 20px;
    text-transform: uppercase;
    font-weight: 600;
    border-radius: 0.25rem;
    border: 1px solid;
    border-inline-start-width: 5px;
    margin-right: var(--ifm-spacing-horizontal);
    text-align: center;
    flex-shrink: 0;
}
```

and then something like this for the different types:

```css
.get > .menu__link::before {
    content: 'get';
    background-color: var(--ifm-color-info-contrast-background);
    color: var(--ifm-color-info-contrast-foreground);
    border-color: var(--ifm-color-info-dark);
}
```

We decided to use the `--ifm-color-(info|warning|danger|success|secondary)-*` colors instead of the OpenAPI colors provided by this package because it matched what we wanted better. It also made it easy to copy the color schemes of docusaurus' admonitions, which already have enough contrast. The current version looks like this:

Dark mode: 
![image](https://user-images.githubusercontent.com/17786332/189295966-35107055-47ba-4224-840e-a59c8e807b38.png)

Light mode: 
![image](https://user-images.githubusercontent.com/17786332/189296079-36b042d0-1f51-479f-8d0a-893c85b29df8.png)
