### ISSUE TITLE
Allow for a `description` to be attached to an API Response Example

### ISSUE THREAD

**Issue by r-colvin** [PaloAltoNetworks/docusaurus-openapi-docs#283]
### Is your feature request related to a problem?
- No

It would be hugely beneficial to be able to provide users with a description of what a response means, especially in the case of an error. It should be one description per example

### Describe the solution you'd like

a spec such as
```
content:
   application/json:
     examples:
         ABC
              description: a description of this response
               value:
                   key: value
```

with a result such as 

![image](https://user-images.githubusercontent.com/18327771/192559372-d7fb37c3-3feb-4be5-8a4b-ff108cd2602a.png)
