### ISSUE TITLE
Schema properties don't indicate if property can be null

### ISSUE THREAD

**Issue by colin-mckibben-sp** [PaloAltoNetworks/docusaurus-openapi-docs#387]
### Is your feature request related to a problem?

OpenAPI supports the ability to mark schema properties as null by setting the `nullable: true` property.  We used to use Redoc to generate our spec, which indicated which properties can be null with a tag:

![image](https://user-images.githubusercontent.com/75683148/213563465-5bbbaead-fb8b-4ab4-9274-c0b8502df7eb.png)

Docusaurus has no visual indication if a property can be null.

![image](https://user-images.githubusercontent.com/75683148/213563765-d4ec3986-7308-4789-b7b5-8f47840243c1.png)

The OpenAPI definition for the `scope` property is as follows:

```yaml
scope:
    type: array
    nullable: true
    items:
      type: string
      default: "sp:scopes:all"
    description: Scopes of the personal  access token.
    example: [ "demo:personal-access-token-scope:first", "demo:personal-access-token-scope:second" ]
```

### Describe the solution you'd like

I would like to see a visual indicator for each property that can be null.

### Describe alternatives you've considered

None

### Additional context

Knowing which properties can potentially return `null` is helpful for consumers of the spec so they know when they need to handle these edge cases in their code.
