### ISSUE TITLE
Please add summary and description to examples

### ISSUE THREAD

**Issue by paulo-raca** [PaloAltoNetworks/docusaurus-openapi-docs#398]
One of my arguments has several examples, with summaries and descriptions.

e.g., 

```yaml
FilterQueryParam:
  in: query
  name: filter
  schema:
    type: string
  description: A filter to be applied to the search using the [SCIM 2.0 Filter syntax](https://www.rfc-editor.org/rfc/rfc7644#section-3.4.2.2).
  examples:
    region:
      summary: Returns only people in a region
      description: Geographic filtering is good for whatever
      value: region eq "BR"
    has_phone:
      summary: Returns only people with phone numbers
      description: Just in case I want to call them
      value: phone_number pr
    has_email:
      summary: Returns only people with email addresses
      description: To compile a spam list
      value: email_address pr
```

### Current Output

This tool currently ignores the summary and description and just outputs this

> Example (region): region eq "BR"
> Example (has_phone): phone_number pr
> Example (has_email): email_address pr

### Expected output 

Maybe something like this?

> Examples:
>   1. Returns only people in a region
>
>       Geographic filtering is good for whatever
>
>       ```region eq "BR"```
>
>   2. Returns only people with phone numbers
>
>       Just in case I want to call them
>
>       ```phone_number pr```
>
>   3. Returns only people with email addresses
>
>       To compile a spam list
>
>       ```email_address pr```
