### ISSUE TITLE
[FR] Do not show `(from schema)` if example provided explicitly

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#438]
### Is your feature request related to a problem?

It's a minor thing, but if I provide an `example` key to the response schema, I see that it's used in the default `Example (from schema)` tab, which is awesome.  But it would be even more awesome of the "from schema" wasn't included, since it's not generated data but explicit values that I've filled out.

### Describe the solution you'd like

Detect the presence of a `responses.X.content.X.schema.example`, and if found, just call the example `Example` instead of `Example (from schema)`

### Additional context
Here's what I'm seeing currently:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/4616705/219096906-c12a8f8c-3966-4813-b957-c15995338f4b.png">

**Comment by sserrata** [comment]
Hi @IanVS, "from schema" is akin to saying the example if inferred from the schema properties, whether each property has an `example` or `default` defined or not. 

That said, when I think of what an "explicit" example is, I think of  `example` or `examples` that can be statically defined, which I believe is different from the inferred "Example (from schema)".

Hope I explained that correctly 😅. I am open to dropping the "from schema" label but I'd also like to prevent possible tab label/value collisions.

**Comment by IanVS** [comment]
Does it make a difference that I'm not setting examples on properties, but rather at the top of `schema`?

```yaml
          schema:
            type: object
            required:
              - data
              - metadata
            properties:
              data:
                type: array
                items:
                  $ref: '../../schemas/AuditLog.yaml'
              metadata:
                $ref: '../../schemas/PaginationMetadata.yaml'
            example:
              data:
                id: log-F3TTIDMKZH5XFH37RTRLIP3TOA
                organizationID: org-F63A24JGCLJV3ZEUTLCBISGETA
                timestamp: 2023-02-15T13:59:09.828868Z
                actor:
                  id: dnkey-DXALSPQONG7H45QZAVTPRDMAPU
                  name: example api key
                  type: apiKey
                target:
                  id: role-LO4SPDSWTZNJC676WFCZKUB3ZQ
```
