### ISSUE TITLE
Display scope for non OAuth security schemes

### ISSUE THREAD

**Issue by guitaoliu** [PaloAltoNetworks/docusaurus-openapi-docs#451]
## Describe the bug

OpenAPI 3.1.0 allows scopes to be defined for security schemes other than OAuth:

- https://github.com/OAI/OpenAPI-Specification/issues/1366
- https://github.com/OAI/OpenAPI-Specification/pull/1829

In a case where we define the API spec for endpoints protected by a customized JWT access token, we would expect the access token to define the scopes that the user can access. Although OpenAPI 3.1 is not officially supported by this project, it should be possible to adopt this feature. 

## Expected behavior

Both of the following securitySchemes should render the `scopes` under `Authorization`. 

```yaml
security:
  - petstore_auth:
      - "write:pets"
      - "read:pets"
  - api_key: 
      - "write:pets"
      - "read:pets"

securitySchemes:
    petstore_auth:
      description: |
        Get access to data while protecting your account credentials.
        OAuth2 is also a safer and more secure way to give you access.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://petstore.swagger.io/api/oauth/dialog"
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      description: >
        For this sample, you can use the api key `special-key` to test the
        authorization filters.
      type: apiKey
      name: api_key
      in: header
```
