### ISSUE TITLE
Support for deepObjects in query parameters

### ISSUE THREAD

**Issue by tyler-mairose-sp** [PaloAltoNetworks/docusaurus-openapi-docs#583]
## Documentation link

N/A

## Describe the problem

Request for improvement.

We are looking for support for the deepObject notation. Given the following example specification:

```yaml
name: query
in: query
description: |
  Allows for pagination and sorting.
required: false
schema:
  type: object
  properties:
    limit:
      type: integer
      description: The limit of results to return
      example: 100
    offset:
      type: integer
      description: The number of records to offset
      example: 50
    order:
      type: string
      description: The attribute to order by
      example: created_at
style: deepObject
explode: true
```

Today the plugin loads in the query parameter, but does not describe anything about the properties of the schema (limit, offset, order).

## Suggested fix

We would like to see described in the UI the ability to use the deepObject notation as follows:

/users?query[limit]=100&query[offset]=2

We would also like to see the description and example for each property under the query parameter `query`
