### ISSUE TITLE
When adding a ":" symbol in the URL, an error occurs during the request

### ISSUE THREAD

**Issue by LGodzilla** [PaloAltoNetworks/docusaurus-openapi-docs#621]
## Documentation link

[buildPostmanRequest Github Docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/buildPostmanRequest.ts)

```
//buildPostmanRequest.ts


function setPathParams(postman: sdk.Request, queryParams: Param[]) {
  const source = queryParams.map((param) => {
    return new sdk.Variable({
      key: param.name,
      value: param.value || `:${param.name}`,
    });
  });
  postman.url.variables.assimilate(source, false);
}


```

```
yaml

paths:
  /User/{id}/page:get:
    parameters:
      - name: id
        in: path
        description: 
        required: true
        schema:
          type: string
          format: 9527
```

baseUrl: [https://api.user.server ↗](https://api.user.server/)
path: /User/{id}/page:get
Compiled path: /User/:id/page:get
The variable {id} has been transformed to ":id" and the constant ":get" to a similar format, where "id" is a variable and ":get" is a fixed parameter.
Assuming the id is 9527,
When clicking "Send API Request",
The desired outcome is:
https://api.user.server/User/:9527/page:get

However, the current result is:
https://api.user.server/

The path content is missing.
I would like to add ":" in the path to support filling without the need for "/" and ensure normal request functionality.
