### ISSUE TITLE
Non-required yaml spec fields showing as required in generated documentation

### ISSUE THREAD

**Issue by outofthisworld** [PaloAltoNetworks/docusaurus-openapi-docs#823]
## Describe the bug
 My yaml spec doc contains the following non-required headers for a POST endpoint:
```
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: false
        - schema:
            type: string
          in: header
          name: X-Api-Key
          required: false
        - schema: {}
          in: header
          name: X-Request-Id
          required: false
```
 After generating my API's yaml spec  in a cloned version of the github example project recommended in the docs, the UI shows these headers as 'required'. I have attached an image below. 

On a side note and unrelated to this issue, I was wondering if someone could elaborate on how endpoints are grouped in the sidebar of the docs. 

I have each endpoint in my api tagged with a tag specific to the resource. E.G /pets endpoints get the tag "pets" (incl del, put,patch) - and the same for other resources. The sidebar nav seems to group everything randomly, rather than the endpoints by their associated tag. Swagger displays them exactly how I would have expected and groups them by this tag. Is there a way I can accomplish a similar thing using this plugin?

## Expected behavior

Non-required headers should not be labeled as required.

## Current behavior

The opposite of above.

## Possible solution
Fix UI.

## Steps to reproduce
1. Clone recommended git project
2. Generate docs from a spec with non-required headers
3. Serve project
4. View output

## Screenshots
<img width="641" alt="Screenshot 2024-05-15 at 11 18 07 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/8555871/2d623a2a-e144-45a4-8a9e-733e48d0c25f">

## Context
Just inaccurate.

## Your Environment
Node 19, using cloned example repo from main github project page.
