### ISSUE TITLE
readOnly property on object is ignored

### ISSUE THREAD

**Issue by christina-gagnon-sp** [PaloAltoNetworks/docusaurus-openapi-docs#830]
## Describe the bug

Object still appears in request schema when ```readOnly``` property is set to true at the object level.

## Expected behavior

The entire object should be excluded from the request schema when ```readOnly``` property is set to true at the object level.   ReDoc renders the schema correctly, so it appears to be a Docusaurus issue.

## Current behavior

```readOnly``` is set to true on the ```ownerRef```object, but the ```ownerRef``` object is still visible in the request schema.

## Steps to reproduce

1. Set ```readOnly: true``` at object level in schema
2. Object still appears in request schema

```
ownerRef:
    type : object
    readOnly: true
    description: >-
      The owner of this template, and the owner of campaigns generated from this template via a schedule. This field
      is automatically populated at creation time with the current user.
    properties:
      id:
        type: string
        description: Id of the owner
        example: 2c918086676d3e0601677611dbde220f
      type:
        type: string
        enum:
          - IDENTITY
        description: Type of the owner
        example: IDENTITY
      name:
        type: string
        description: Name of the owner
        example: Mister Manager
      email:
        type: string
        description: Email of the owner
        example: mr.manager@example.com
```

## Screenshots

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/97126282/9d6c6a09-b62f-4401-ab4e-021f98568eed)

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/97126282/2ab1b4bc-8d53-4a7b-9f3d-885a1053a638)

## Context

We need to be able to exclude entire objects, not just individual properties from the request schema.

## Your Environment

- Version used: 2.4.3
- Environment name and version: node.js v20.12.2, npm 10.5.0, python 3.12.3
- Operating System and version (desktop or mobile): Win 11 Pro
