### ISSUE TITLE
 Example & externalDocs attributes not displaying

### ISSUE THREAD

**Issue by MaartenDCrius** [PaloAltoNetworks/docusaurus-openapi-docs#885]
### Example & externalDocs attributes not displaying

In our api spec we add example values for our properties and externalDocs. These are not displayed in the output

```
      properties:
        label:
          maxLength: 50
          minLength: 0
          type: string
          description: Label of the license plan
        rateLimitTokens:
          type: integer
          description: Amount of API requests the customer can do in one hour
          format: int32
          example: 1000
          externalDocs:
            description: Rate limiting
            url: https://exampleUrl.com
```

### Describe the solution you'd like

Possible solution:

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/32892964/14c4c706-abda-42be-83a2-6c9689d33707)

### Describe alternatives you've considered

We used Swizzling to add our own SchemaItem component
