### ISSUE TITLE
oneOf creates strange-looking schema

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#889]
## Describe the bug

When creating a schema with 

```yaml
oneOf:
    - type: string
    - type: object
```

The resulting schema in the docs is a `oneOf` selector button with a single option that's a string.

## Expected behavior

AFAIK this is a valid use of `oneOf`, but maybe I'm wrong.  I'm going off the "Mixed types" section here: https://swagger.io/docs/specification/data-models/data-types/

## Current behavior

See screenshot below

## Possible solution

I think it should probably just say `object | string` or something like that.  

## Steps to reproduce

in the demo in this repo:

1. Find the "post /pet" responses in the definition file
2. Add this response:
	```
	"200":
          description: All good
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    oneOf:
                      - type: string
                      - type: object
	```
3. Notice that it looks like this:
<img width="344" alt="image" src="https://github.com/user-attachments/assets/be9fef55-167a-45dc-9d2a-6dc256c76773">

## Context

I have a response key that can sometimes be a string and sometimes be an object, depending on details in the request, and I'm trying to create a schema to represent that.
