### ISSUE TITLE
Way to edit api base url 

### ISSUE THREAD

**Issue by Muneer-Shafi** [PaloAltoNetworks/docusaurus-openapi-docs#935]
![image](https://github.com/user-attachments/assets/88c291a2-bb14-4ab4-8f20-1a9fc96ad489)
i want to edit the url before sending request to the server 
here in my case tenant is dynamic and client side user can change it before requesting to the server
current  working show dropdown list of servers but not editable

**Comment by aszenz** [comment]
Related https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/609

**Comment by sserrata** [comment]
Hi @aszenz, this has been possible for years. Although it's not explicitly documented, the demo APIs provide an example of using variables in the `servers` definition. The trick is to not provide an `enum` key, which is normally used when you want to provide predefined variables for users to select from. By leaving `enum` out the user will be presented with a text input. The `default` value will be the text input placeholder.

<img width="545" alt="Screenshot 2024-08-27 at 11 17 31 AM" src="https://github.com/user-attachments/assets/c631cb01-7ee2-4433-9904-47c6e3babc1f">

Example snippet:

```
servers:
  - url: https://{tenant}.example.dev
    description: Testing variable with user input
    variables:
      tenant:
        default: tenant
```
