### ISSUE TITLE
Array with enum values in items: nested description not displayed

### ISSUE THREAD

**Issue by AnnikaStrupp-initAG** [PaloAltoNetworks/docusaurus-openapi-docs#942]
## Describe the bug

The generated documentation does not display a 'description' text provided on the level of 'enum' in array 'items'.

## Expected behavior

The 'description' is rendered and displayed on screen. This would be particularly useful for `§ref` referenced codelists in 'items' that come with their own descriptions.

## Current behavior

The generated documentation does not display a 'description' text provided on the level of 'enum' in array 'items'. The specified set of 'enum' values is correctly displayed as 'Possible values'.

## Steps to reproduce

example-array .yaml
```yaml
  example:
    type: array
    items:
      enum:
        - 1
        - 2
        - 3
        - string
      description: >
        This description is sadly not rendered.
```

<img width="207" alt="example" src="https://github.com/user-attachments/assets/7e598c59-5271-4de3-8350-9623cd4a3787">

### Version used:
- node.js 20.12.1
- Docusaurus OpenAPI Docs 3.0.1
- Windows desktop
